config/routes.rb
Rails.application.routes.draw do
  devise_for :staff_users, controllers: {
    registrations: 'staff_users/registrations',
    sessions: 'staff_users/sessions'
  }
  devise_for :owners, controllers: {
    registrations: 'owners/registrations',
    sessions: 'owners/sessions'
  }
  root to: 'shift_requests#index'
  resources :shift_requests, only: [:index, :create] do
    collection do
      get 'search'
      post 'submit'
    end
  end
  resources :boards, only: [:index, :create, :update] do
    member do
      get 'search'
      post 'invite'
    end
    resources :shifts, only: [:index, :create, :update, :destroy] do
      collection do
        get 'weekly'
        get 'monthly'
        get 'calendar'
        get 'search'
        post 'share'
      end
    end
  end
end

app/views/shared/_board_list.html.erb
<div class="side-bar-header">
  <div class="board-creation">
    <%= form_with model: @board, local: true do |f| %>
      <div class="new-board-name">
        <%= f.label '新規シフトボードの作成', class: "new-board-title" %>
      </div>
      <div class="new-board-form_left">
        <%= f.text_field :name, class: "new-board-name-input", placeholder: "例）〇〇支店のシフト" %>
      </div>
      <div class="new-board-form_right">
        <%= f.submit '作成', class: "board-create-btn" %>
      </div>
    <% end %>
  </div>
</div>

<div class="side_bar_content">
  <% @boards.each do |board| %>
    <div class="board-name">
      <%= link_to board.name, board_shifts_path(board), class: "board-name-link" %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="error-alert">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <% unless owner_signed_in? || staff_user_signed_in? %>
    <div class="header__top">
      <div class="header-content">
        <div class="header__left">
          <%= link_to new_owner_session_path, class: "header__top-owner" do %>
            <span class="owner-link-mark">▶︎</span><span>事業主様はこちら</span>
          <% end %>
        </div>
        <div class="header__right">
          <%= link_to 'メールでのお問い合わせ', "#", class: "header__top-contact" %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="main__header">
    <div class="header-content">
      <div class="header__left">
        <%= link_to root_path do%>
          <h1>ShiftLink</h1>
        <% end %>
      </div>
      <div class="header__right">
        <% if owner_signed_in? %>
          <%= link_to "#{current_owner.last_name} #{current_owner.first_name}", boards_path, class: 'owner_name' %>
          <%= link_to 'ログアウト', destroy_owner_session_path, method: :delete, class: "logout" %>
        <% elsif staff_user_signed_in? %>
          <%= link_to "#{current_staff_user.last_name} #{current_staff_user.first_name}", root_path, class: 'staff_name' %>
          <%= link_to 'ログアウト', destroy_staff_user_session_path, method: :delete, class: "logout" %>
        <% else %>
          <div>
            <%= link_to 'ログイン', new_staff_user_session_path, class: "login" %>
            <%= link_to 'アカウント登録', new_staff_user_registration_path, class: "sign-up" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_inner_shift_cell.html.erb
<div class="shift-content shift-content__top" data-date=<%= l(date, format: :default) %>>
  <div class="shift-content-exist">
    <div class="shift-time-wrapper">
      <% shifts.each do |shift| %>
        <div class="each-shift-time-content" data-shift=<%= shift.id %> data-decided=<%= shift.decided %>>
          <div class="one-shift-time">
            <p class="shift-time">
              <%= "#{l(shift.start_time, format: :short)} - #{l(shift.end_time, format: :short)}" %>
            </p>
            <div class="shift-menu-icon">
              <i class="fas fa-ellipsis-h"></i>
              <ul class="shift-menu-list">
                <li class="shift-menu-edit">編集する</li>
                <li class="shift-menu-delete">
                  <%=link_to '削除する', "/boards/#{@board.id}/shifts/#{shift.id}", method: :delete %>
                </li>
              </ul>
            </div>
          </div>
          <%# シフト時間の編集 ここから %>
            <div class="shift-edit-content">
              <h3>シフトを変更</h3>
              <p class="form-head-shift-staff-name">
                <%= staff.last_name %> <%= staff.first_name %>
              </p>
              <p class="form-head-shift-date">
                <%= l(date, format: :long) %>
              </p>
              <%= form_with model: [@board, shift], local:true do |f| %>
                <%= hidden_field_tag :id, shift.id %>
                <%= hidden_field_tag :staff_user_id, staff.id %>
                <div class="shift-form-time-group">
                  <%= f.time_select :start_time, default: shift.start_time, minute_step: 5 %>
                  <span class="between-start-end">-</span>
                  <%= f.time_select :end_time, default: shift.end_time, minute_step: 5 %>
                </div>
                <div class="shift-form-btn-group">
                  <button type="button" class="shift-edit-form-cancel">キャンセル</button>
                  <%= f.submit '変更', class: "shift-edit-form-submit" %>
                </div>
              <% end %>
            </div>
          <%# シフト時間の編集 ここまで %>
        </div>
      <% end %>
    </div>
    <%# シフトの追加ページ ここから %>
    <div class="shift-create-content">
      <h3>シフトを追加</h3>
      <p class="form-head-shift-staff-name">
        <%= staff.last_name %> <%= staff.first_name %>
      </p>
      <p class="form-head-shift-date">
        <%= l(date, format: :long) %>
      </p>
      <%= form_with model: [@board, @shift], class: "shift-add-form", local: true do |f| %>
        <%= hidden_field_tag :staff_user_id, staff.id %>
        <div class="shift-form-time-group">
          <%= f.time_select :start_time, class:"start-form-box", default: date.in_time_zone, minute_step: 5 %>
          <span>-</span>
          <%= f.time_select :end_time, class: "end-form-box", default: date.in_time_zone, minute_step: 5 %>
        </div>
        <div class="shift-form-btn-group">
          <button type="button" class="shift-create-form-cancel">キャンセル</button>
          <%= f.submit '保存', class: "shift-create-form-submit" %>
        </div>
      <% end %>
    </div>
    <%# シフトの追加ページ ここまで %>
  </div>
</div>

app/views/shared/_inner_shift_request.html.erb
<div class="shift-content" data-date=<%= l(date, format: :default) %>>
  <div class="shift-content-exist">
    <div class="shift-time-wrapper">
      <% shift_requests.each do |shift_request| %>
        <div class="each-shift-time-content">
          <div class="one-shift-time">
            <p class="shift-time" data-shiftr=<%= shift_request.id %>>
              <%= "#{l(shift_request.start_time, format: :short)} - #{l(shift_request.end_time, format: :short)}" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_modal.html.erb
<div id="board-show-modal">
  <div id="board-edit-content">
    <%= form_with model: @board, url: "/boards/#{@board.id}", id: "edit-form" do |f| %>
      <h3>シフトボード名の変更</h3>
      <div class="board-name-edit-input">
        <%= f.text_field :name, id: "board-edit-name" %>
      </div>
      <div class="board-edit-btn-group">
        <button type="button" class="board-edit-form-cancel" id="edit-close-btn">キャンセル</button>
        <%= f.submit '変更する', id: "edit-submit-btn" %>
      </div>
    <% end %>
  </div>

  <div id="board-invite-content">
    <button type="button" class="modal-close-btn" id="invite-close-btn">×</button>
    <h3 class="invite-header-text">ボードに招待</h3>
    <%= form_with model: @board_staff, url: "/boards/#{@board.id}/search", id: "invite-form" do |f| %>
      <div class="search-staff-name-group">
        <%= f.label :id_name, 'ユーザーID' %>
        <%= f.text_field :id_name, id: "invite-staff-name" %>
      </div>
      <button type="button" id="search-staff-btn">検索する</button>
      <p id="result-staff-name"></p>
      <p id="result-message"></p>
      <button  type="button", id="invite-staff-submit" >招待する</button>
    <% end %>
  </div>
</div>

app/views/shared/_second_header.html.erb
<header class="second-header">
  <div class='board-show-header'>
    <div class="board-header-left">
      <nav class="board-list-menu">
        <div class="board-list-menu-btn" id="board-list-menu">
          <i class="fas fa-angle-down fa-lg"></i>
        </div>
        <ul class="board-list-pulldown" id="board-list-pulldown" style="display:none;">
          <% current_owner.boards.each do |board| %>
            <li class="pulldown-list-each-board">
              <%= link_to board.name, board_shifts_path(board), class: "pulldown-board-link", id:"pulldown-board-link" %>
            </li>
          <% end %>
        </ul>
      </nav>
      <div class="board-name-btn" id="board-name-btn">
        <h2 id="board-name-text"><%= @board.name %></p>
      </div>

      <div class="invite-btn-wrapper">
        <i class="fas fa-user-plus lg" id="invite-btn"></i>
      </div>

      <div class="staff-list-wrapper">
        <% @staffs.each do |staff| %>
          <div class="member-list">
            <%= link_to "#{staff.last_name}", "#", class: "board-staff-link" %>
          </div>
        <% end %>
        <div id="add-staff"></div>
      </div>
    </div>
    <div class="share-button">
      <%= link_to 'シフト共有', "/boards/#{@board.id}/shifts/search" %>
    </div>
    <div class="board-header-right">
      <div class="current-user-wrapper">
        <%= link_to "#{current_owner.last_name} #{current_owner.first_name}", boards_path, class: 'owner_name' %>
        <%= link_to 'ログアウト', destroy_owner_session_path, method: :delete, class: "logout" %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_switch_button.html.erb
<div class="switch-bar">
  <% if params[:start_date] == nil %>
    <div id="switch-weekly" class="switch">
      <%= link_to '週', "/boards/#{@board.id}/shifts/weekly" %>
    </div>
    <div id="switch-monthly" class="switch">
      <%= link_to '月', "/boards/#{@board.id}/shifts/monthly" %>
    </div>
    <div id="switch-calendar" class="switch">
      <%= link_to 'カレンダー', "/boards/#{@board.id}/shifts/calendar" %>
    </div>
  <% else %>
    <div id="switch-weekly" class="switch">
      <%= link_to '週', "/boards/#{@board.id}/shifts/weekly?start_date=#{params[:start_date]}" %>
    </div>
    <div id="switch-monthly" class="switch">
      <%= link_to '月', "/boards/#{@board.id}/shifts/monthly?start_date=#{params[:start_date]}" %>
    </div>
    <div id="switch-calendar" class="switch">
      <%= link_to 'カレンダー', "/boards/#{@board.id}/shifts/calendar?start_date=#{params[:start_date]}" %>
    </div>
  <% end %>
</div>