config/routes.rb
Rails.application.routes.draw do
  devise_for :staff_users, controllers: {
    registrations: 'staff_users/registrations',
    sessions: 'staff_users/sessions'
  }
  devise_for :owners, controllers: {
    registrations: 'owners/registrations',
    sessions: 'owners/sessions'
  }
  root to: 'shift_requests#index'
  resources :shift_requests, only: [:index, :create] do
    collection do
      get 'search'
      post 'submit'
    end
  end
  resources :boards, only: [:index, :create, :update] do
    member do
      get 'search'
      post 'invite'
    end
    resources :shifts, only: [:index, :create, :update, :destroy] do
      collection do
        get 'weekly'
        get 'monthly'
        get 'calendar'
        get 'search'
        post 'share'
      end
    end
  end
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :board
  belongs_to :staff_user

  with_options presence: true do
    validates :start_time
    validates :end_time
  end

  validate :not_before_start, :not_change_date, :not_doubling

  def not_before_start
    errors.add(:end_time, 'は開始時間より前の時間は指定できません') if start_time > end_time
  end

  def not_change_date
    errors.add(:end_time, 'は開始時間と異なる日付は指定できません') unless (start_time.all_day).cover?(end_time)
  end

  def not_doubling
    unless id.present?
      same_date_shifts = Shift.where(staff_user_id: staff_user_id, board_id: board_id, start_time: start_time.all_day)
      same_date_shifts.each do |shift|
        errors.add(:base, '同じユーザーに既に登録されている期間と重複するものは指定できません') if shift.start_time <= end_time && shift.end_time >= start_time
      end
    end
  end

  def self.search(params)
    start_term = Time.zone.parse(params[:start_term]).midnight if params[:start_term].present?
    end_term = Time.zone.parse(params[:end_term]).end_of_day if params[:end_term].present?
    Shift.where(board_id: params[:board_id], start_time: start_term..end_term, decided: nil)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :except_owner
  before_action :correct_owner
  before_action :index_set, only: [:index, :monthly, :weekly, :calendar, :create]
  before_action :header_set, only: [:index, :monthly, :weekly, :calendar, :create, :search]

  def index
  end

  def monthly
  end

  def weekly
  end

  def calendar
  end

  def create
    @board = Board.find(params[:board_id])
    @shift = Shift.new(shift_params)
    if @shift.valid?
      @shift.save
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def update
    shift = Shift.find(params[:id])
    if shift.decided != true
      shift.update(shift_params)
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def destroy
    if shift.decided != true
      shift = Shift.find(params[:id])
      shift.destroy
      redirect_to request.referer
    end
  end

  def search
    @search_params = search_params
    if @search_params[:start_term].present? && search_params[:end_term].present?
      @shifts = Shift.search(@search_params).includes(:board, :staff_user).order(start_time: 'ASC')
      session[:search] = @shifts.ids
    else
      render :search
    end
  end

  def share
    ids = session[:search]
    if ids.length != 0
      shifts = Shift.where(id: ids).includes(:board, :staff_user)
      shifts.update(decided: true)
      ids.clear
      redirect_to board_shifts_path(@board.id)
    else
      render :search
    end
  end

  private

  def shift_params
    params.require(:shift).permit(:start_time, :end_time).merge(staff_user_id: params[:staff_user_id], board_id: params[:board_id])
  end

  def search_params
    params.fetch(:search, {}).permit(:start_term, :end_term).merge(board_id: params[:board_id])
  end

  def except_owner
    redirect_to root_path unless owner_signed_in?
  end

  def correct_owner
    @board = Board.find(params[:board_id])
    redirect_to boards_path if current_owner.id != @board.owner.id
  end

  def header_set
    @board = Board.find(params[:board_id])
    gon.board_id = @board.id
    gon.board_name = @board.name
    @board_staff = BoardStaff.new
    @staffs = @board.staff_users
    gon.board_staffs_id = @staffs.map { |s| s[:id] }
  end

  def index_set
    @shifts = @board.shifts.includes(:staff_user, :board)
    @shift = Shift.new
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/calendar.html.erb
<%= render "shared/second_header" %>

<div id='board-show-main'>
  <%# 月カレンダー %>
  <div class="month-calendar" id="month-calendar">
    <div class="shift-title">
      <%= month_calendar do |date|%>
      <% end %>
      <%= render 'shared/switch_button' %>
    </div>
    <div class="month-calendar-main">
      <%= month_calendar(events: @shifts) do |date, shifts| %>
        <div class="month-day">
          <%= date.day %>
        </div>
        <div class="month-day-staff">
          <% shifts.each do |shift| %>
            <% staff = StaffUser.find(shift.staff_user_id) %>
            <%= "#{staff.last_name}" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%# モーダルウィンドウ %>
  <%= render 'shared/modal' %>
</div>

app/views/shifts/index.html.erb
<%= render "shared/second_header" %>

<div id='board-show-main'>
  <%# 月 シフト %>
  <div class="month-shift" id="month-shift">
    <div class="shift-title">
      <%= month_calendar do |date|%>
      <% end %>
      <%= render 'shared/switch_button' %>
    </div>
    <div class="shift-table">
      <div class="date-row">
        <div class="empty"></div>
        <div class="date-list">
          <%= month_calendar do |date|%>
            <p>
              <span class="date-date"><%= date.day %></span>
              (<span class="date-wday-name"><%= t('date.day_names')[date.wday] %></span>)
            </p>
          <% end %>
        </div>
      </div>
      <% @staffs.each do |staff| %>
        <div class="staff-shift-list">
          <div class="staff-cell">
            <%= "#{staff.last_name} #{staff.first_name}" %>
          </div>
          <div class="staff-shift-group" data-staff=<%= staff.id %>>
            <div class="staff-shift__top">
              <%= month_calendar(events: staff.shifts.where(board_id: @board.id)) do |date, shifts| %>
                <%= render partial: 'shared/inner_shift_cell', locals: { date: date, shifts: shifts, staff: staff } %>
              <% end %>
            </div>
            <div class="staff-shift-request__bottom">
              <%= month_calendar(events: staff.shift_requests.where(board_id: @board.id, submitted: true)) do |date, shift_requests| %>
                <%= render partial: 'shared/inner_shift_request', locals: { date: date, shift_requests: shift_requests, staff: staff } %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%# モーダルウィンドウ %>
  <%= render 'shared/modal' %>

</div>

app/views/shifts/monthly.html.erb
<%= render "shared/second_header" %>

<div id='board-show-main'>
  <%# 月 シフト %>
  <div class="month-shift" id="month-shift">
    <div class="shift-title">
      <%= month_calendar do |date|%>
      <% end %>
      <%= render 'shared/switch_button' %>
    </div>
    <div class="shift-table">
      <div class="date-row">
        <div class="empty"></div>
        <div class="date-list">
          <%= month_calendar do |date|%>
            <p>
              <span class="date-date"><%= date.day %></span>
              (<span class="date-wday-name"><%= t('date.day_names')[date.wday] %></span>)
            </p>
          <% end %>
        </div>
      </div>
      <% @staffs.each do |staff| %>
        <div class="staff-shift-list">
          <div class="staff-cell">
            <%= "#{staff.last_name} #{staff.first_name}" %>
          </div>
          <div class="staff-shift-group" data-staff=<%= staff.id %>>
            <div class="staff-shift__top">
              <%= month_calendar(events: staff.shifts.where(board_id: @board.id)) do |date, shifts| %>
                <%= render partial: 'shared/inner_shift_cell', locals: { date: date, shifts: shifts, staff: staff } %>
              <% end %>
            </div>
            <div class="staff-shift-request__bottom">
              <%= month_calendar(events: staff.shift_requests.where(board_id: @board.id, submitted: true)) do |date, shift_requests| %>
                <%= render partial: 'shared/inner_shift_request', locals: { date: date, shift_requests: shift_requests, staff: staff } %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%# モーダルウィンドウ %>
  <%= render 'shared/modal' %>
</div>

app/views/shifts/search.html.erb
<%= render 'shared/second_header' %>

<div class="submit-wrapper">
  <div class="submit-main">
    <%= form_with(scope: :search, url: "/boards/#{@board.id}/shifts/search", local: true, method: :get, class: "submit-search-form") do |f| %>
      <%= f.date_field :start_term, value: @search_params[:start_term] %>
      <%= f.date_field :end_term, value: @search_params[:end_term] %>
      <%= f.submit "確認する" %>
    <% end %>
  </div>
</div>

<% if @shifts.present? %>
  <div class="submit-confirm">
    <ul>
      <% @shifts.each do |shift| %>
        <li>
          <p>
            <%= l(shift.start_time, format: :date_long) %>
            <%= "#{shift.staff_user.last_name} #{shift.staff_user.first_name}" %>
            <%= "#{l(shift.start_time, format: :short)} - #{l(shift.end_time, format: :short)}" %>
          </p>
        </li>
      <% end %>
    </ul>
    <div>
      <div class="submit-btn-wrapper">
        <%= link_to 'キャンセル', "/boards/#{@board.id}/shifts" %>
        <%= link_to '共有する', share_board_shifts_path, method: :post %>
      </div>
    </div>
  </div>
<% end %>

app/views/shifts/weekly.html.erb
<%= render "shared/second_header" %>

<div id='board-show-main'>
  <%# 週 シフト %>
  <div class="week-shift" id="week-shift">
    <div class="shift-title">
      <%= week_calendar do |date|%>
      <% end %>
      <%= render 'shared/switch_button' %>
    </div>
    <div class="shift-table">
      <div class="date-row">
        <div class="empty"></div>
        <div class="date-list">
          <%= week_calendar do |date|%>
            <p>
              <span class="date-date"><%= date.day %></span>
              (<span class="date-wday-name"><%= t('date.day_names')[date.wday] %></span>)
            </p>
          <% end %>
        </div>
      </div>
      <% @staffs.each do |staff| %>
        <div class="staff-shift-list">
          <div class="staff-cell">
            <%= "#{staff.last_name} #{staff.first_name}" %>
          </div>
          <div class="staff-shift-group">
            <div class="staff-shift__top">
              <%= week_calendar(events: staff.shifts) do |date, shifts| %>
                <%= render partial: 'shared/inner_shift_cell', locals: { date: date, shifts: shifts, staff: staff } %>
              <% end %>
            </div>
            <div class="staff-shift-request__bottom">
              <%= week_calendar(events: staff.shift_requests.where(board_id: @board.id, submitted: true)) do |date, shift_requests| %>
                <%= render partial: 'shared/inner_shift_request', locals: { date: date, shift_requests: shift_requests, staff: staff } %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%# モーダルウィンドウ %>
  <%= render 'shared/modal' %>

</div>