config/routes.rb
Rails.application.routes.draw do
  devise_for :staff_users, controllers: {
    registrations: 'staff_users/registrations',
    sessions: 'staff_users/sessions'
  }
  devise_for :owners, controllers: {
    registrations: 'owners/registrations',
    sessions: 'owners/sessions'
  }
  root to: 'shift_requests#index'
  resources :shift_requests, only: [:index, :create] do
    collection do
      get 'search'
      post 'submit'
    end
  end
  resources :boards, only: [:index, :create, :update] do
    member do
      get 'search'
      post 'invite'
    end
    resources :shifts, only: [:index, :create, :update, :destroy] do
      collection do
        get 'weekly'
        get 'monthly'
        get 'calendar'
        get 'search'
        post 'share'
      end
    end
  end
end

app/models/shift_request.rb
class ShiftRequest < ApplicationRecord
  belongs_to :board
  belongs_to :staff_user

  with_options presence: true do
    validates :start_time
    validates :end_time
  end

  validate :not_before_start, :not_change_date, :not_doubling

  def not_before_start
    errors.add(:end_time, 'は開始時刻より前の時刻は指定できません') if start_time.present? && end_time.present? && start_time > end_time
  end

  def not_change_date
    if start_time.present? && end_time.present? && !(start_time.all_day).cover?(end_time)
      errors.add(:end_time, 'は開始時刻と異なる日付は指定できません')
    end
  end

  def not_doubling
    if start_time.present? && end_time.present? && id.blank?
      same_date_shifts = ShiftRequest.where(staff_user_id: staff_user_id, start_time: start_time.all_day)
      same_date_shifts.each do |shift|
        errors.add(:base, '同じユーザーに既に登録されている期間と重複するものは指定できません') if shift.start_time <= end_time && shift.end_time >= start_time
      end
    end
  end

  def self.search(params)
    start_term = Time.zone.parse(params[:start_term]).midnight if params[:start_term].present?
    end_term = Time.zone.parse(params[:end_term]).end_of_day if params[:end_term].present?
    ShiftRequest.where(board_id: params[:board_id], staff_user_id: params[:staff_user_id], start_time: start_term..end_term, submitted: false)
  end
end

app/controllers/shift_requests_controller.rb
class ShiftRequestsController < ApplicationController
  before_action :visit_owner, except: [:index]
  before_action :visit_no_login_user, except: [:index]

  def index
    if staff_user_signed_in?
      @shift_requests = current_staff_user.shift_requests.includes(:staff_user, :board)
      @shifts = current_staff_user.shifts.where(decided: true).includes(:staff_user, :board)
      @shift_request = ShiftRequest.new
    end
  end

  def create
    @shift_request = ShiftRequest.new(shift_request_params)
    if @shift_request.valid?
      @shift_request.save
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def search
    @search_params = search_params
    if @search_params[:board_id].present? && @search_params[:start_term].present? && @search_params[:end_term].present?
      @shift_requests = current_staff_user.shift_requests.search(@search_params).includes(:board, :staff_user).order(start_time: 'ASC')
      session[:search] = @shift_requests.ids
    else
      render :search
    end
  end

  def submit
    ids = session[:search]
    if ids.length != 0
      shift_requests = current_staff_user.shift_requests.where(id: ids).includes(:board, :staff_user)
      shift_requests.update(submitted: true)
      ids.clear
      redirect_to root_path
    else
      render :search
    end
  end

  private

  def shift_request_params
    params.require(:shift_request).permit(:start_time, :end_time, :board_id).merge(staff_user_id: current_staff_user.id, submitted: false)
  end

  def search_params
    params.fetch(:search, {}).permit(:board_id, :start_term, :end_term).merge(staff_user_id: current_staff_user.id)
  end

  def visit_owner
    redirect_to root_path if owner_signed_in?
  end

  def visit_no_login_user
    redirect_to root_path unless owner_signed_in? || staff_user_signed_in?
  end
end

app/helpers/shift_requests_helper.rb
module ShiftRequestsHelper
end

app/views/shift_requests/index.html.erb
<%= render 'shared/header' %>

<% if staff_user_signed_in? %>
  <div class="staff-main">
    <div class="staff-calendar" id="requested-shift-calendar" style="display:none;">
      <div class="shift-title">
        <%= month_calendar do |date| %>
        <% end %>
        <%= link_to 'シフト提出', search_shift_requests_path %>
        <div class="calendar-switch-btn-group">
          <button type="button" class="switch-shift__right" id="r_f-btn">確定済シフト</button>
          <button type="button" class="switch-shift__left" id="r_r-btn">希望シフト</button>
        </div>
      </div>
      <div class="month-calendar-main">
        <%= month_calendar(events: @shift_requests) do |date, shift_requests| %>
          <div class="staff-date-content">
            <div class="month-day">
              <%= date.day %>
            </div>
            <div class="except-month-day">
              <div class="month-day-staff">
                <% shift_requests.each do |shift_request| %>
                  <% if shift_request.submitted == true %>
                    <i class="fas fa-check-circle"></i>
                  <% end %>
                  <%= shift_request.board.name %>
                  <%= "#{l(shift_request.start_time, format: :short)} - #{l(shift_request.end_time, format: :short)}" %>
                <% end %>
              </div>
              <div class="shift-request-add">
                <%= form_with model: @shift_request, url: shift_requests_path, local: true do |f| %>
                  <h3>シフト希望の追加</h3>
                  <div class="staff-board-select">
                    <%= f.collection_select :board_id, current_staff_user.boards, :id, :name, { include_blank: '選択してください' }, { required: true } %>
                  </div>
                  <div class="shift-form-time-group">
                    <%= f.time_select :start_time, class:"start-form-box", default: date.in_time_zone, minute_step: 5 %>
                    <span>-</span>
                    <%= f.time_select :end_time, class: "end-form-box", default: date.in_time_zone, minute_step: 5 %>
                  </div>
                  <div class="staff-form-btn-group">
                    <button type="button" class="staff-add-shift-cancel">キャンセル</button>
                    <%= f.submit '保存', class: "staff-add-shift-submit" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="staff-calendar" id="fixed-shift-calendar">
      <div class="shift-title">
        <%= month_calendar do |date|%>
        <% end %>
        <div class="calendar-switch-btn-group">
          <button type="button" class="switch-shift__right" id="f_f-btn">確定済シフト</button>
          <button type="button" class="switch-shift__left" id="f_r-btn">希望シフト</button>
        </div>
      </div>
      <div class="month-calendar-main">
        <%= month_calendar(events: @shifts) do |date, shifts| %>
          <div class="month-day">
            <%= date.day %>
          </div>
          <div class="month-day-staff">
            <% shifts.each do |shift| %>
              <%= shift.board.name %>
              <%= "#{l(shift.start_time, format: :short)} - #{l(shift.end_time, format: :short)}" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div id="staff-modal-overlay"></div>

<% else %>
  <div class="home-main">
    <div class="top-wrapper">
      <div class="top-container">
        <div class="catch__left">
          <h2>シフト管理が、カンタンに</h2>
          <h1>ShiftLink</h1>
          <p>ここに文章が入ります。ここに文章が入ります。</p>
          <p>ここに文章が入ります。</p>
          <div class="btn-wrapper">
            <%= link_to 'アカウント登録', new_staff_user_registration_path, class: "top-sign-up" %>
            <%= link_to 'ログイン', new_staff_user_session_path, class: "top-login" %>
          </div>
        </div>
        <div class="catch__right">
          <%= embedded_svg("Calendar_Monochromatic.svg", class: "calendar_monochromatic", alt: "top-image") %>
        </div>
      </div>
    </div>
    <div class="service"></div>
  </div>
<% end %>

app/views/shift_requests/search.html.erb
<%= render 'shared/header' %>

<div class="submit-wrapper">
  <div class="submit-main">
    <%= form_with(scope: :search, url: search_shift_requests_path, local: true, method: :get, class: "submit-search-form") do |f| %>
      <%= f.collection_select :board_id, current_staff_user.boards, :id, :name, { include_blank: '選択してください', selected: @search_params[:board_id] }, { required: true } %>
      <%= f.date_field :start_term, value: @search_params[:start_term] %>
      <%= f.date_field :end_term, value: @search_params[:end_term] %>
      <%= f.submit "確認する" %>
    <% end %>
  </div>
</div>

<% if @shift_requests.present? %>
  <div class="submit-confirm">
    <ul>
      <% @shift_requests.each do |shift_request| %>
        <li>
          <p>
            <%= l(shift_request.start_time, format: :date_long) %>
            <%= "#{l(shift_request.start_time, format: :short)} - #{l(shift_request.end_time, format: :short)}" %>
          </p>
        </li>
      <% end %>
    </ul>
    <div>
      <div class="submit-btn-wrapper">
        <%= link_to 'キャンセル', root_path %>
        <%= link_to '提出する',submit_shift_requests_path, method: :post %>
      </div>
    </div>
  </div>
<% end %>